const opps = [
  {
    firstName: "Muhammad",
    lastName: "Ali",
    abilities: ["boxing", "strong"],
    win: true,
  },
  {
    firstName: "T-rex",
    lastName: "from Jurassic world",
    abilities: ["teeth", "bite", "scary"],
    win: true,
  },
  {
    firstName: "Oleg",
    lastName: "Ponyatyshyn",
    abilities: ["master coder", "volleyball", ""],
    win: false,
  },
  {
    firstName: "Muhammad",
    lastName: "Ali's dog",
    abilities: ["teeth", "bite", "scary"],
    win: false,
  },
  {
    firstName: "Peely",
    lastName: "from Fortnite",
    abilities: ["Fortnite Battlepass"],
    win: false,
  },
  {
    firstName: "Genghis",
    lastName: "Khan",
    abilities: ["red", "yellow", "black"],
    win: true,
  },
  {
    firstName: "Fnord",
    lastName: "Peggleblast",
    abilities: ["Supirior Guide", "mlp reject"],
    win: false,
  },
  {
    firstName: "Chief",
    lastName: "the Cow",
    abilities: ["babymaker3000", "chick magnet", "chaRIZZma"],
    win: true,
  },
  {
    firstName: "Master",
    lastName: "Oogway",
    abilities: ["Kung Fu"],
    win: true,
  },
  {
    firstName: "Kratos",
    lastName: "God of War",
    abilities: [
      "Stamina",
      "Speed",
      "Healing",
      "Immortality",
      "Power Nullification",
      "Rage",
      "Electricity Manipulation",
      "Intelligence",
      "Shapeshifting",
      "Strength",
      "Superhuman agility",
      "Time Manipulation",
    ],
    win: true,
  },
  {
    firstName: "Figment",
    lastName: "of imagination",
    abilities: ["purple"],
    win: false,
  },
  {
    firstName: "Terrance",
    lastName: "Angry Birds",
    abilities: ["round", "big", "red"],
    win: true,
  },
];
