const opps = [
  {
    firstName: "Muhammad",
    lastName: "Ali",
    abilities: ["round"],
    win: true,
  },
  {
    firstName: "T-rex",
    lastName: "from Jurassic world",
    abilities: ["red", "yellow", "black"],
    win: true,
  },
  {
    firstName: "Oleg",
    lastName: "Ponyatyshyn",
    abilities: ["red", "yellow", "black"],
    win: false,
  },
  {
    firstName: "Muhammad",
    lastName: "Ali's dog",
    abilities: ["red", "yellow", "black"],
    win: false,
  },
  {
    firstName: "Peely",
    lastName: "from Fortnite",
    abilities: ["red", "yellow", "black"],
    win: false,
  },
  {
    firstName: "Genghis",
    lastName: "Khan",
    colors: ["yellow"],
    abilities: ["red", "yellow", "black"],
    win: true,
  },
  {
    firstName: "Fnord",
    lastName: "Peggleblast",
    abilities: ["red", "yellow", "black"],
    win: false,
  },
  {
    firstName: "Chief",
    lastName: "the Cow",
    colors: ["yellow"],
    abilities: ["red", "yellow", "black"],
    win: true,
  },
  {
    firstName: "Master",
    lastName: "Oogway",
    abilities: ["red", "yellow", "black"],
    win: true,
  },
  {
    firstName: "Kratos",
    lastName: "God of War",
    abilities: ["red", "yellow", "black"],
    win: true,
  },
  {
    firstName: "Figment",
    lastName: "of imagination",
    abilities: ["red", "yellow", "black"],
    win: false,
  },
  {
    firstName: "Terrance",
    lastName: "Angry Birds",
    abilities: ["red", "yellow", "black"],
    win: true,
  },
];
